import Phaser from 'phaser';

export const EventBus = new Phaser.Events.EventEmitter();

export const GameEvents = {
  PLAYER_HEALTH_CHANGED: 'player:health',
  PLAYER_MANA_CHANGED: 'player:mana',
  PLAYER_EXP_CHANGED: 'player:exp',
  PLAYER_LEVEL_UP: 'player:levelup',
  PLAYER_DIED: 'player:died',
  MONSTER_DIED: 'monster:died',
  COMBAT_DAMAGE: 'combat:damage',
  SKILL_USED: 'skill:used',
  ITEM_PICKED: 'item:picked',
  ITEM_DROPPED: 'item:dropped',
  ZONE_ENTERED: 'zone:entered',
  ZONE_EXIT: 'zone:exit',
  LOG_MESSAGE: 'log:message',
  NPC_INTERACT: 'npc:interact',
  SHOP_OPEN: 'shop:open',
  SHOP_CLOSE: 'shop:close',
  DIALOGUE_CLOSE: 'dialogue:close',
  INVENTORY_OPEN: 'inventory:open',
  INVENTORY_CLOSE: 'inventory:close',
  INVENTORY_CHANGED: 'inventory:changed',
  QUEST_ACCEPTED: 'quest:accepted',
  QUEST_COMPLETED: 'quest:completed',
  QUEST_TURNED_IN: 'quest:turned_in',
  QUEST_FAILED: 'quest:failed',
  ACHIEVEMENT_UNLOCKED: 'achievement:unlocked',
  HOMESTEAD_UPGRADED: 'homestead:upgraded',
  ITEM_DISCARDED: 'item:discarded',
  SAVE_GAME: 'save:game',
  LOAD_GAME: 'load:game',
  UI_SKILL_CLICK: 'ui:skill_click',
  UI_TOGGLE_PANEL: 'ui:toggle_panel',
  COMBAT_STATE_CHANGED: 'combat:state_changed',
  MINIBOSS_DIALOGUE: 'miniboss:dialogue',
  LORE_COLLECTED: 'lore:collected',
  RANDOM_EVENT_TRIGGERED: 'random_event:triggered',
  RANDOM_EVENT_RESOLVED: 'random_event:resolved',
  HIDDEN_AREA_DISCOVERED: 'hidden_area:discovered',
  STORY_DECORATION_INTERACT: 'story_decoration:interact',
  SUBDUNGEON_ENTER: 'subdungeon:enter',
  SUBDUNGEON_EXIT: 'subdungeon:exit',
  DUNGEON_ENTER: 'dungeon:enter',
  DUNGEON_FLOOR_CHANGE: 'dungeon:floor_change',
  DUNGEON_EXIT: 'dungeon:exit',
  DUNGEON_BOSS_KILLED: 'dungeon:boss_killed',
} as const;
